In [1]:
import pandas as pd 
import numpy as np 
import matplotlib as plt 
import seaborn as sns

In [2]:
dataset = pd.read_csv('SAML-D.csv')

In [3]:
dataset.head()

,Time,Date,Sender_account,Receiver_account,Amount,Payment_currency,Received_currency,Sender_bank_location,Receiver_bank_location,Payment_type,Is_laundering,Laundering_type
0,10:35:19,2022-10-07,8724731955,2769355426,1459.15,UK pounds,UK pounds,UK,UK,Cash Deposit,0,Normal_Cash_Deposits
1,10:35:20,2022-10-07,1491989064,8401255335,6019.64,UK pounds,Dirham,UK,UAE,Cross-border,0,Normal_Fan_Out
2,10:35:20,2022-10-07,287305149,4404767002,14328.44,UK pounds,UK pounds,UK,UK,Cheque,0,Normal_Small_Fan_Out
3,10:35:21,2022-10-07,5376652437,9600420220,11895.00,UK pounds,UK pounds,UK,UK,ACH,0,Normal_Fan_In
4,10:35:21,2022-10-07,9614186178,3803336972,115.25,UK pounds,UK pounds,UK,UK,Cash Deposit,0,Normal_Cash_Deposits

In [4]:
dataset.tail()

,Time,Date,Sender_account,Receiver_account,Amount,Payment_currency,Received_currency,Sender_bank_location,Receiver_bank_location,Payment_type,Is_laundering,Laundering_type
9504847,10:57:01,2023-08-23,2453933570,519744068,2247.25,UK pounds,UK pounds,UK,UK,ACH,0,Normal_Small_Fan_Out
9504848,10:57:06,2023-08-23,9805510177,5416607878,927.18,UK pounds,UK pounds,UK,UK,Debit card,0,Normal_Small_Fan_Out
9504849,10:57:06,2023-08-23,7282330957,2995527149,1455.14,UK pounds,UK pounds,UK,UK,ACH,0,Normal_Small_Fan_Out
9504850,10:57:11,2023-08-23,940337377,4812815165,25995.70,UK pounds,UK pounds,UK,UK,ACH,0,Normal_Fan_In
9504851,10:57:12,2023-08-23,105185176,6824994831,9586.08,UK pounds,UK pounds,UK,UK,ACH,0,Normal_Fan_Out

In [6]:
dataset.describe()

       Sender_account  Receiver_account        Amount  Is_laundering
count    9.504852e+06      9.504852e+06  9.504852e+06   9.504852e+06
mean     5.006619e+09      5.006006e+09  8.762968e+03   1.038733e-03
std      2.885814e+09      2.884763e+09  2.561495e+04   3.221263e-02
min      9.018000e+03      9.018000e+03  3.730000e+00   0.000000e+00
25%      2.513133e+09      2.513219e+09  2.143688e+03   0.000000e+00
50%      5.001017e+09      5.002572e+09  6.113720e+03   0.000000e+00
75%      7.505051e+09      7.502397e+09  1.045846e+04   0.000000e+00
max      9.999987e+09      9.999971e+09  1.261850e+07   1.000000e+00